David mision2
AkariWorksDev/WebLearn pull request #3
Opened 2020-05-06 10:37 UTC by Dtar380

He acabado coregidme

2020-05-06 11:07 UTC, borjalan requested changes
Añade los cambios que faltan y vuelve a pushearlos.

2020-05-06 11:07 UTC, borjalan commented on David/mision2/index.html
> +
No has puesto ningún título. Dentro de la etiqueta title en la parte de su contenido tienes que poner el titulo de la página.

2020-05-06 11:07 UTC, borjalan commented on David/mision2/index.html
> +  </body>
Faltan las etiquetas que dice la misión que hay que poner. Paso 9 al final. Lee bien las instrucciones, tienes que añadir a , img , br , p , h1 , input , button , div , title , !--

2020-05-06 15:25 UTC, Dtar380 commented on David/mision2/index.html
> +  </body>
ok

2020-05-06 15:26 UTC, Dtar380 commented on David/mision2/index.html
> +  </body>
¿podría añadir etiquetas extra?

2020-05-07 07:52 UTC, borjalan approved these changes
Lee las aclaraciones y cuando las entiendas puedes mergear.

2020-05-07 07:52 UTC, borjalan commented on David/mision2/index.html
> +    <!--Esta etiqueta se emplea para luego dar aspecto con CSS-->
Las etiquetas div son divisores. Si no les añades un atributo class y luego añades un fichero .css no sirven para lo que estás diciendo.

2020-05-07 07:52 UTC, borjalan commented on David/mision2/index.html
> +        <artcle>
Aquí has puesto **artcle** en vez de **article**

2020-05-07 07:52 UTC, borjalan commented on David/mision2/index.html
> +          <input>Aqui puedes escribir</input>
Es un formulario de texto.

2020-05-07 07:52 UTC, borjalan commented on David/mision2/index.html
> +      <aside>
Un **aside** es una sección de una página que consiste en contenido que está indirectamente relacionado con el contenido principal del documento

2020-05-07 07:54 UTC, borjalan commented on David/mision2/index.html
> +    <!--Esta etiqueta se emplea para luego dar aspecto con CSS-->
Puedes poner por ejemplo 
`<div class="clase1"></div>`
Y luego en un archivo css añadirle estilos a la clase clase1

2020-05-07 07:56 UTC, merged